### ISSUE TITLE
Specify license in package.json

### ISSUE THREAD

**Issue by pcguru** [dchest/tweetnacl-js#100]
It would be nice if you could state the license in package.json. This would make it possible to use a [license-checker](https://www.npmjs.com/package/license-checker) to verify that all packages in a project complies with the Author's intentions.

You could simply state "Public Domain" in package.json, but do note that there is no such thing in countries like Germany. It would be better if you could distribute this code under one of the popular licenses such as Apache 2, BSD, ISC or MIT?

**Comment by dchest** [comment]
Please see all previous issues. It seems like the only purpose of this issue tracker is to talk about licenses.

**Comment by yxhuvud** [comment]
People continue to raise questions about licenses because it still is an issue people actually run into. 

One way to resolve the issue could be to do a dual licensing solution. Let the users choose either PD or ISC (or whatever you find best).
