### ISSUE TITLE
Bad Key Size

### ISSUE THREAD

**Issue by Silom** [dchest/tweetnacl-js#101]
Hello,

I get the error: "Bad public key size", when I try to open my Box with a 48 Byte Shared-Key.
I changed the configs in nacl.box to have my actual key length, but my configs doesn't get applied for some reason.

    // I tried both, to be sure
    nacl.box.publicKeyLength = publicKey.length;
    nacl.box.sharedKeyLength = publicKey.length;

Any suggestions, or have I found a bug?
This error doesn't make a lot of sense in the scenario.

**Comment by dchest** [comment]
How did you get a 48-byte shared key? It should be 32 bytes.

**Comment by dchest** [comment]
BTW, there are no configs, everything is fixed. You're changing constants, which are provided for user's convenience.

**Comment by Silom** [comment]
Hey @dchest,

thanks for the fast reply. I consume backend data and just got a 48 Byte key. I will tell our service guys to fix it by turning it into a 32 Byte Key. I wasn't sure who is doing it wrong, me or the service guys, but thats my answer right here.
Cheers!

**Comment by dchest** [comment]
Perhaps they are using some other ECC crypto, not Curve25519? 48-byte key would probably come from 192-bit curve, such as secp192k1. Or maybe it's hashed with SHA-384?

**Comment by Silom** [comment]
Oh well called them. They will fix it they said, nothing I know about details.
