### ISSUE TITLE
sealed box missing

### ISSUE THREAD

**Issue by steverweber** [dchest/tweetnacl-js#102]
https://download.libsodium.org/doc/
sealed_boxes.html

One way encryption so a pub key can encrypt data but only the private key can dec.

**Comment by dchest** [comment]
TweetNaCl-js is a port of [TweetNaCl](https://tweetnacl.cr.yp.to/)/[NaCl](http://nacl.cr.yp.to/) to JavaScript. "Sealed boxes" is a construction created by libsodium authors, it's not in the original NaCl (likewise, there is no password hashing, BLAKE2, etc.).

I like the concept of sealed boxes, and if somebody implements them on top of TweetNaCl-js (which is pretty easy to do), I'll be happy to include link to README (as already the case with many extensions, even written by myself — [tweetnacl-auth-js](https://github.com/dchest/tweetnacl-auth-js) and [nacl-stream-js](https://github.com/dchest/nacl-stream-js), or by others, see [this list](https://github.com/dchest/tweetnacl-js#third-party-libraries-based-on-tweetnacljs)).
