### ISSUE TITLE
Prefer little-endian for `dl64()` and `ts64()`?

### ISSUE THREAD

**Issue by shelby3** [dchest/tweetnacl-js#103]
I noticed you are using big-endian for these functions which load and store to `Uint8Array` (8-bit byte buffers).

Wouldn't it be preferred to use little-endian in case in the future someone wanted to optimize some critical code paths with native code interopting with some JavaScript portions?

Note that [Berstein wrote](https://cr.yp.to/snuffle/salsafamily-20071225.pdf#page=9), “_Most current CPUs take extra time for big-endian accesses, while big-endian CPUs generally have good support for little-endian accesses_”.

**Comment by dchest** [comment]
These are for SHA-512. If you change the byte order, it will no longer be SHA-512.

**Comment by shelby3** [comment]
Ah yes, I see it is only used for SHA-512 and SHA-2 forces the use of big-endian.

Apparently many of the [modern hash functions don't force big-endian](http://crypto.stackexchange.com/questions/2099/why-do-all-hash-functions-use-big-endian-data).
