### ISSUE TITLE
License as SPDX identifier

### ISSUE THREAD

**Issue by hpurmann** [dchest/tweetnacl-js#107]
Hello!

My company is [automatically checking licenses](https://github.com/actano/advocate) of installed modules by using the `license` key in the `package.json`. Unfortunately, this module does not provide a [SPDX-valid entry](https://docs.npmjs.com/files/package.json#license).

Do you think this is possible? Having
```javascript
{
  license: "Public domain",
}
```
would  help us as well. We'd appreciate it :)

**Comment by dchest** [comment]
Unfortunately, there's no SPDX for public domain. Please search this issue tracker mentioning this for more details about licensing.

**Comment by hpurmann** [comment]
Wow, that was quick. Sorry for not searching the existing issues first.

I saw people specifying "Public domain" as a license identifier in their `package.json`. So what you are saying is that these people are wrong doing so because "Public domain" is not a license?

**Comment by dchest** [comment]
Indeed, it's not correct, and npm even started complaining about it: https://github.com/dchest/tweetnacl-js/commit/cd9f8e4230691e581eec6e12a006dacf8b753b94

As for why SPDX won't specify it, see http://wiki.spdx.org/view/Legal_Team/Decisions/Dealing_with_Public_Domain_within_SPDX_Files

**Comment by dchest** [comment]
I have an idea though! https://github.com/dchest/tweetnacl-js/pull/108/commits/9e65910bc37797e26a620893e688f5afb41772b6

What do you think? :)

**Comment by dchest** [comment]
> are saying is that these people are wrong doing so because "Public domain" is not a license?

I mean, they are technically incorrect (NPM shows warning and SPDX doesn't have this string), not legally — legally it may be okay (IANAL).

**Comment by hpurmann** [comment]
Yeah, https://github.com/dchest/tweetnacl-js/pull/108/commits/9e65910bc37797e26a620893e688f5afb41772b6 would help us, thank you 👍
