### ISSUE TITLE
Semantic Versioning

### ISSUE THREAD

**Issue by dbrgn** [dchest/tweetnacl-js#112]
Does this project follow [semantic versioning](http://semver.org/)? If yes, could you state it in the CHANGELOG?

Would be good to know when creating libraries that depend on tweetnacl. If I can be sure that semver is followed, I can depend on version `0.14.x`.

**Comment by dchest** [comment]
I try to follow semver, yes, but I'll announce if I commit to it when 1.0 is released. For now the answer is that you can depend on version 0.14.x, even though semver doesn't guarantee it:

> 4. Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.

**Comment by dbrgn** [comment]
You're right. I was under the impression that the minor version needs to be incremented for incompatible updates even for 0.x releases, which is wrong :)

Thanks for the information!
