### ISSUE TITLE
Are you open to the idea of a code audit?

### ISSUE THREAD

**Issue by hazinstore** [dchest/tweetnacl-js#115]
Hello!
I'm planning to rely on NACL for a number of important crypto tasks in a new verified identity protocol we're working on, which is intended to replace x509 and the current CA system,  Lofty goals, I know.  In the meantime, since our reference implementation has both C and JS versions, I am wondering if you would be open to the idea of a code audit to ensure byte for byte compatibility with the original tweet nacl you derived from.

From there we plan to audit tweet nacl itself and submit any patches then back port them to tweetnacl.js, so it's going to form a pretty heavy cycle.

Thank you in advance!

**Comment by dchest** [comment]
Yes, please!

**Comment by alax** [comment]
Just a heads up, Cure53 (https://cure53.de/) will be performing a formal audit of this library at the end of January.

**Comment by hazinstore** [comment]
Oh ok then, maybe we can contribute to that in order to avoid duplication of efforts.
Thanks for the heads up!

**Comment by dchest** [comment]
Huge thanks to @alax and Deletype for sponsoring the audit. It's not published here: https://github.com/dchest/tweetnacl-js#audits
