### ISSUE TITLE
Types for nacl-fast

### ISSUE THREAD

**Issue by ernieturner** [dchest/tweetnacl-js#116]
I'm fairly new to trying out Typescript, so there might be an easy way to do this, so apologies in advance if this is an easy solution.

I'm including the `nacl-fast.js` file in a module like `import * as nacl from "tweetnacl/nacl-fast"` but the issue I'm seeing is that because I'm including the `nacl-fast` file, TypeScript won't find the `nacl.d.ts` file because of file name differences. I tried doing a quick symlink within my local `node_modules` directory to symlink `nacl.d.ts` to `nacl-fast.d.ts` and that seems to have appeased TypeScript (as the exposed API of both those files is identical).

So would it be possible to expose a `nacl-fast.d.ts` file as well (probably just a simple copy as part of the NPM build step)? Or maybe there's a way to tell TypeScript to use a types file that is under a different name? This is the part that my lack of TypeScript understanding is having trouble with.

Thanks for any help in advanced.

**Comment by dchest** [comment]
Hm, since nacl-fast.js is the default module now,  `import * as nacl from "tweetnacl"` should do it. Does it work that way?

**Comment by ernieturner** [comment]
Apologies, you're correct. I hadn't noticed the `main` entry in the package.json file that made nacl-fast the default. So yes, this is working as expected then. Sorry about that.

I really appreciate the library, thanks for all the work!

**Comment by dchest** [comment]
Now worries, thanks for trying it! If you notice something that can be improved or have a question, don't hesitate to open another issue.
