### ISSUE TITLE
Convert ed25519 to curve25519

### ISSUE THREAD

**Issue by JustinDrake** [dchest/tweetnacl-js#117]
TweetNaCl is awesome, but it seems to be missing two helper functions for my needs, namely:

* ed25519 public key to curve25519 public key
* ed25519 private key to curve25519 private key

I am assuming these functions are easy to implement. Do you know if these helper functions are publicly available somewhere in JavaScript? Would you consider adding these helper functions to TweetNaCl?

**Comment by dchest** [comment]
Sure thing — https://github.com/dchest/ed2curve-js 😄

**Comment by JustinDrake** [comment]
You're awesome, thanks!
