### ISSUE TITLE
Implementation of Anonymous Public-key Encryption (Sealed Boxes)

### ISSUE THREAD

**Issue by yangwao** [dchest/tweetnacl-js#118]
Hello, your library is really cool, but I miss sealed boxes (anonymous public-key encryption). 
Had idea to implement it or hint for library to use? Thanks.

For reference https://download.libsodium.org/doc/public-key_cryptography/sealed_boxes.html 

> Simple public key encryption allows for sending anonymous encrypted messages to a recipient given its public key. Only the recipient can decrypt these messages, using its private key.
While the recipient can verify the integrity of the message, it cannot verify the identity of the sender.
https://rdrr.io/cran/sodium/man/simple.html

**Comment by dchest** [comment]
Please see #102

**Comment by yangwao** [comment]
Oh, thanks!
