### ISSUE TITLE
checkArrayTypes is fragile

### ISSUE THREAD

**Issue by rongarret** [dchest/tweetnacl-js#119]
checkArrayTypes uses the following hack to determine if an object is an Uint8Array:

Object.prototype.toString.call(thing) !== '[object Uint8Array]'

This breaks if someone installs a new toString method in the Object prototype (which one might want to do to assist in debugging).  A more reliable way to check whether an object is of a particular type is to look at its constructor, i.e.:

thing.constructor == Uint8Array

**Comment by dchest** [comment]
Thanks for suggestion! What about `thing instanceof Uint8Array`?

**Comment by rongarret** [comment]
That would probably work too, but note that instanceof doesn't have quite the same semantics as checking the identity of the constructor because instanceof walks up the prototype chain.  I can't think of a situation where this would matter, but I'm not really a JS wizard.

**Comment by dchest** [comment]
I think it's actually good that it walks the prototype chain, since it will work with Node.js Buffers (which switched to Uint8Array in v4 or something like that):

```js
> var a = new Buffer(10)
undefined
> a instanceof Uint8Array
true
> a.constructor === Uint8Array
false
```

**Comment by rongarret** [comment]
It's a judgement call.  Making crypto code more permissive increases the attack surface.  I can't think of any attack that using instanceof would enable, so I think it would be fine either way.  Personally, I like to err on the safe side, but it's your decision.

**Comment by dchest** [comment]
To be fair, I would skip typecheck at all — it's JavaScript after all; but people are too used to passing strings when we expect Uint8Arrays, so it's better be here. I don't think this has any influence on attack surface — it's just a simple check against programmer errors.

**Comment by desudesutalk** [comment]
I vote for check with `instanceof` (because of node.js)

@dchest by the way, will you accept PR with `HMAC` and `pbkdf2` functions? I have code what uses lowlevel api for both of this with sha512. I can make it part of your library.

**Comment by dchest** [comment]
> @dchest by the way, will you accept PR with HMAC and pbkdf2 functions? I have code what uses lowlevel api for both of this with sha512. I can make it part of your library.

No, I'd like to keep this package strictly the port of TweetNaCl. FYI, there's https://github.com/dchest/tweetnacl-auth-js for HMAC.

**Comment by desudesutalk** [comment]
Ok, I see. And thanks for link!

**Comment by rongarret** [comment]
Something else you might want to consider then is just to make a separate check_type function that can be overridden by the user in the same way that randomBytes can be.
