### ISSUE TITLE
"SCRIPT0: secure random number generation not supported by this browser use chrome, FireFox or Internet Explorer 11"

### ISSUE THREAD

**Issue by omryr** [dchest/tweetnacl-js#122]
im using a library that is using this one and im getting this error when running in IE 11, did anyone encounter it? and if yes what was the solution? i am looking for a few hours now and kinda lost, would appreciate any help.
thanks!

**Comment by dchest** [comment]
Can you please provide more details. Which library and what version of tweetnacl-js?

**Comment by omryr** [comment]
version 0.14.5 and the library is ethereumjs-wallet

**Comment by dchest** [comment]
It looks like the error is coming from https://github.com/crypto-browserify/randombytes/blob/master/browser.js which `browserify` uses for bundles to replace Node's `crypto.randomBytes`, so the library doesn't use our `nacl.randomBytes`.

**Comment by omryr** [comment]
ah ok thanks ill check it with hem i guess :), if by any chance you know the solution it would be cool too :)
