### ISSUE TITLE
How do I generate a nonce (for the box encryption)?

### ISSUE THREAD

**Issue by NullVoxPopuli** [dchest/tweetnacl-js#123]
I'm new to NaCl and the idea of a nonce, but how do I generate a secure nonce?
I've seen other NaCl libraries do this for me (like the ruby one).
If I generate a nonce, how would I send it to the receiver so they can open my message?

**Comment by dchest** [comment]
There are two popular ways to handle nonces, depending on the protocol:

* You generate it randomly (`nacl.randomBytes(24)`) and then send to the receiver in plaintext along with the message. The receiver then uses this nonce to open the message. This is usually done when encrypting files for storage (nonce is appended or prepended to the encrypted data) or when sender and receiver communicate asynchronously and replay attacks is not relevant or handled in a different level of protocol.

* Both sides keep a nonce as a counter of messages and increment it for each message. In this case, make sure that either the keys for sending and receiving are different or use nonce separation, e.g. `"Server" + counter` would be used for server's messages `"Client" + counter` for client's. In this case, you don't need to send nonce along with the message.

In general, if you don't know what to do with the nonce, it means that you're trying to design your own protocol. If you're new to cryptography, this can be dangerous, as even experience protocol designers make mistakes, so I suggest you to look up for a suitable protocol for your purpose, which was designed and vetted (e.g. has an RFC [but not all of them] or described in a national standard). For further questions, I'd suggest https://crypto.stackexchange.com/.

Thanks.

**Comment by NullVoxPopuli** [comment]
Thanks for the in-depth explanation! -- that's kind of the hunch I had about how it would work, but I wanted to be sure -- it reminds me of how RSA + AES are used together to encrypt long messages with Public/Private Keys. 

I'm using tweetnacl-js in a side project of mine, where I try to make a p2mesh chat client.
https://github.com/NullVoxPopuli/tanqueReact

So, based on your information (I'm going with the prepending method) -- I have this (untested, as I need to leave for work soon)
```
import * as NaCl from 'tweetnacl';
import * as randomBytes from 'random-bytes';

export function encryptFor(messageWithoutNonce, theirPublicKey, mySecretKey) {
  const nonce = newNonce();
  const message = `${nonce}${messageWithoutNonce}`;
  const box = NaCl.box(message, nonce, theirPublicKey, mySecretKey);

  return box;
}

export function decryptFrom(messageWithNonce, theirPublicKey, mySecretKey) {
  const nonce = 0;
  const message = messageWithNonce; // TODO: break out the prepended nonce

  const box = NaCl.box(message, nonce, theirPublicKey, mySecretKey);
  const decrypted = NaCl.box.open(box, nonce, theirPublicKey, mySecretKey);

  return decrypted;
}

export function newNonce() {
  return randomBytes.sync(24);
}
```

**Comment by NullVoxPopuli** [comment]
for any future readers -- this is what I ended up with: https://github.com/NullVoxPopuli/tanqueReact/blob/550c6ae0d65b296212ce2a16c005b8f4f82f2b9e/js/utility/nacl.js#L23
