### ISSUE TITLE
Cure53’s audit should be verifiable

### ISSUE THREAD

**Issue by joeldrapper** [dchest/tweetnacl-js#127]
The [Audit](https://tweetnacl.js.org/audits/cure53.pdf) conducted by [Cure53](https://cure53.de) should either be hosted on their domain, `https://cure53.de`, or it should be cryptographically signed and verifiable.

They have a [verified](https://cure53.de/keybase.txt) account on Keybase (https://keybase.io/cure53) so they could sign the document using their PGP Public Key.

**Comment by dchest** [comment]
Yeah, it makes some sense to have some verifiable repository for publicly accessible audits. But that's all we have now. I think you can call Cure53 to verify it :)

**Comment by joeldrapper** [comment]
Thanks. I actually just [tweeted](https://twitter.com/JoelDrapper/status/883281454419103744) Cure53 to see if they would be happy to sign it with Keybase. If they’re happy to, that would be ideal.

**Comment by cure53** [comment]
Here you are!

https://cure53.de/tweetnacl.pdf
https://cure53.de/tweetnacl.pdf.signed

**Comment by dchest** [comment]
Awesome, thank you!
