### ISSUE TITLE
Compatibility issues with PHP NaCl ? PHP vs Javascript

### ISSUE THREAD

**Issue by juanjofm** [dchest/tweetnacl-js#129]
Hello guys, I am trying to use this Javascript library with an (old) PHP NaCl implementation (this one https://github.com/devi/Salt) until PHP 7.2 stable with sodium is released.

I don't know if I'm doing anything wrong. I checked codification and tested many things... but, I'm getting different cyphertext for box functions even using the same pair keys and nonce. I wanted to generate keys and encrypt content in Javscript, for example, and decrypt it on PHP and vice versa. But, it didn't work, so I tested generating cyphertext with some nonce and keys and it should be equals but they don't.

For example on the PHP side it generates something like:

"AAAAAAAAAAAAAAAAAAAAAJKh6HhIgGigPuRr8n/MqIj6R/j06VG18w9Ri55l5v6ez4JS9+ZO/ndPzk3Ju6PDVakIafVK1Toqw+zl6G3rxuRbP6IBjuoaOw==" (base64 encoded).

and on Javascript:

"kqHoeEiAaKA+5Gvyf8yoiPpH+PTpUbXzD1GLnmXm/p7PglL35k7+d0/OTcm7o8NVqQhp9UrVOirD7OXobevG5Fs/ogGO6ho7"  (base 64 encoded).

**Comment by dchest** [comment]
This looks like a run of zeros:

```
"AAAAAAAAAAAAAAAAAAAAA
```

So I guess there's something wrong with how you use the PHP library or its implementation.

**Comment by juanjofm** [comment]
Ok, don't worry, this PHP library was supposed to be like based on NaCl and compatible, but, I just tested sodium with PHP 7.2 Beta and it works correctly there, so I will work on the Beta version. Thanks. ;)
