### ISSUE TITLE
AMD support

### ISSUE THREAD

**Issue by nazar-pc** [dchest/tweetnacl-js#133]
I saw #87, but it would be nice to also have AMD (RequireJS) support for completeness

**Comment by dchest** [comment]
I considered AMD, but I don't think there's large enough userbase of AMD anymore, everyone seems to be switching to Node-style `require` build process or ECMAScript modules  ¯\_(ツ)_/¯

**Comment by nazar-pc** [comment]
Build process inevitably introduces overhead and complexity. Having 2 more lines doesn't cost much and can be executed natively in browser. I really see no reason why it shouldn't be supported. ECMAScript modules are nice in theory, but imperative loading is still not there and their usage often requires build processes, which I'm not a big fan of.
