### ISSUE TITLE
Can I use public key to sign message and open by secret key?

### ISSUE THREAD

**Issue by ArronYR** [dchest/tweetnacl-js#135]
hi, in the readme, I can use secret key to sign message and open the signed message by public key.

### nacl.sign(message, secretKey)

Signs the message using the secret key and returns a signed message.

### nacl.sign.open(signedMessage, publicKey)

Verifies the signed message and returns the message without signature.

---

but now, I want someone use my public key encrypt a message, then send to me, I use my secret key to decrypt it.

in this library, has functions like these?
```
nacl.sign(message, publicKey)
nacl.sign.open(signedMessage, secretKey)
```

**Comment by dchest** [comment]
Yes, see `nacl.box` https://github.com/dchest/tweetnacl-js#public-key-authenticated-encryption-box. If you want it to work like RSA, where you don't need sender's public key to decrypt, generate a random ephemeral key pair, use its secret key to box, and send the public key along with ciphertext. Receiver will then combine this public key with their secret key to open the box.

Signing and box keys are different. If you want to use only one key for both, see https://github.com/dchest/ed2curve-js.

**Comment by ArronYR** [comment]
Thank you for your answer.

In `nacl.box`, has these two functions:
```
nacl.box(message, nonce, theirPublicKey, mySecretKey)
nacl.box.open(box, nonce, theirPublicKey, mySecretKey)
```
In your answer, the `mySecretKey` is secret key of generate a random ephemeral key pair, the `theirPublicKey` is my public key. the public key of the random ephemeral key pair is not used, and my secret key is not used too.

it can not achieve such an effect: someone use my public key encrypt a message, then send to me, I use my secret key to decrypt it.

**Comment by ArronYR** [comment]
@dchest thanks. I see the test in here, and solved my question。[https://github.com/dchest/ed2curve-js/blob/master/test/test.js](https://github.com/dchest/ed2curve-js/blob/master/test/test.js)

Thank you very much.
