### ISSUE TITLE
Is the nonce in secretbox sensitive

### ISSUE THREAD

**Issue by istrau2** [dchest/tweetnacl-js#136]
I would like to use tweetnacl to allow my users to encrypt strings using a password and then store the result in a file for them so that they can recover the information using the file + password later. I would like to make the nonce transparent to the users. I was thinking that I could just generate a random nonce and then store it in the file along with the encrypted string. That way, when the user provides the file later to recover, I could just get the nonce from the file and the key from the user. However, I can't find any information on whether or not the nonce is sensitive at all. My guess is that it isn't and that only the secret key is sensitive but I would like to be sure.

Thanks in advance.

**Comment by dchest** [comment]
Yes, your scheme is correct: generate a random nonce *every time* the file is encrypted/re-encrypted and store it along with the encrypted file. However, please make sure you're correctly deriving a encryption key from the password. For example, you can use https://github.com/dchest/scrypt-async-js.

**Comment by istrau2** [comment]
@dchest Ok, thanks for the quick reply.

**Comment by dchest** [comment]
You're welcome. To add to this, nonce is indeed not a secret information: the only requirement for it is to be unique for each message encrypted with the same key. So, it's possible to use a counter if you can make sure it will never repeat, however for file encryption it's best to use a random nonce to avoid any mistakes with nonce repetition.

**Comment by dchest** [comment]
BTW, I highly recommend this book if you want to learn more about proper usage of cryptography: https://www.nostarch.com/seriouscrypto

**Comment by istrau2** [comment]
@dchest ok, ordered. Thanks.

**Comment by istrau2** [comment]
@dchest I am a little lost on this part:

> For example, you can use https://github.com/dchest/scrypt-async-js (you can store salt and parameters used for it also in the file).

That salt should be random right? 
Can I just use:
```
naclUtil.encodeBase64(
            nacl.randomBytes(nacl.secretbox.nonceLength)
        )
```
to generate  the salt?
Given my use case, do I need to specify any of the other options?

**Comment by dchest** [comment]
Yes, the salt should be random, a good choice would be 32 bytes: `nacl.randomBytes(32)`. Yes, you'll need to specify N, r, p parameters, see this blog post for details: https://blog.filippo.io/the-scrypt-parameters/

**Comment by istrau2** [comment]
@dchest Hey, I have completed a first version of this functionality. I was hoping you would be willing to audit the code (want to make sure these files are properly encrypted). You can find the code here:

https://github.com/stellarport/portal/blob/develop/src/app/resources/stellar/keystore-service.js

I am happy to pay for the work in crypto =) (specifically stellar lumens). I am part of the stellarport.io dev team and we are looking to add this to our portal. Maybe after this is deployed you can even create a wallet using the keystore option and I can send you some XLM at that address. 

Thanks in advance.
