### ISSUE TITLE
How to use an existing object/data as secret key?

### ISSUE THREAD

**Issue by KrishnaPG** [dchest/tweetnacl-js#137]
What is the best way to derive a public-key from existing unique data, such as thumbprint of a human being?

I have thumbprint data, and need to use it as secret key to sign, so that the chance of "misplacing" or loosing the secret key (there by losing the access to data) is minimized.

Is such thing possible? Or should we always generate both keys together?

**Comment by dchest** [comment]
It's possible to derive keys from source material (HKDF or a hash function if it's high-entropy, scrypt or PBKDF if it's low-entropy), but of course, the security of it depends on the amount of entropy in it.

I'd suggest using https://crypto.stackexchange.com or https://security.stackexchange.com for such questions.

Thank you!
