### ISSUE TITLE
Is there a way to make `secretbox.overheadLength` changable

### ISSUE THREAD

**Issue by Moejoe90** [dchest/tweetnacl-js#140]
I am having an application where I don't want any overhead when using secret box,

I tried overriding the variable in order to get 0 overhead however that didn't work out, is there a way to do this or maybe add this functionality if it wasn't available.

**Comment by dchest** [comment]
What do you mean, you don't want overhead? This is not a choice, secret box security relies on having 16 bytes of authenticator.
