### ISSUE TITLE
How to use nacl.secretbox.open(box, nonce, key)?

### ISSUE THREAD

**Issue by abrarShariar** [dchest/tweetnacl-js#145]
I cannot open a `secretbox`, getting `false` from `nacl.secretbox.open`. I am passing the encrypted data from `nacl.secretbox(message, nonce, key)`, the **nonce** and **key** are also similar as **secretbox**. What am I doing wrong? Any example would be helpful.

**Comment by joeldrapper** [comment]
Hey @abrarShariar, could you share an example gist?

**Comment by abrarShariar** [comment]
hey @joeldrapper, here goes the [gist](https://gist.github.com/abrarShariar/eb31f0f73fe76676fdb55a919d9be0b4). Attaching the snippet here too for ease:

```
const decryptFile = (filePath, sKey) => {
  fs.readFile(filePath, 'utf8', (err, data) => {
    if (err) throw err;

    let hash = computeSHA256(sKey);
    let buffer = Buffer.from(hash.toString(CryptoJS.enc.Hex), 'hex');
    let key = new Uint8Array(buffer);

    buffer = Buffer.from(data.toString(CryptoJS.enc.Hex), 'hex');
    let encryptedData = new Uint8Array(buffer);

    let decryptedData;
    try {
      decryptedData = nacl.secretbox.open(encryptedData, Rnonc, key);
    } catch (e) {
      console.log("Error in decryptFile: ", e);
    }

    console.log("DecryptedData: ", decryptedData);
  });

```

Basically I have a `decryptFile` function that takes the file path of a `.enc` file which stores encrypted data returned from `nacl.secretbox(message, nonce, key)`.

**Comment by abrarShariar** [comment]
I found the answer [here](https://medium.com/zinc_work/using-cryptography-tweetnacl-js-to-protect-user-data-intro-tips-tricks-a8e38e1818b5). Following the code snippet solved my issue. Others might find that post helpful for understanding tweetnacl.js. Closing this issue.
