### ISSUE TITLE
Elligator support

### ISSUE THREAD

**Issue by rattacresh** [dchest/tweetnacl-js#147]
The version offered does not support the Elligator anti-censorship transformation that makes public keys indistinguishable from random noise

**Comment by dchest** [comment]
Indeed, this is a port of [TweetNacl](http://tweetnacl.cr.yp.to/), so it does whatever TweetNaCl does.

**Comment by rattacresh** [comment]
They are ready made for the C version available at https://github.com/denadmin/TweetNaCl-Elligator/commit/5600b4c1ad35dd7eff25a0f2ab9a2a4610e6ece7 -- shouldn't be hard to adopt, it's just an extension, not a modification!
