### ISSUE TITLE
TypeError: unexpected type, use Uint8Array

### ISSUE THREAD

**Issue by eolszewski** [dchest/tweetnacl-js#148]
## Bug

When calling `nacl.sign.keyPair.fromSeed` from react-scripts, I get the following error:

```
TypeError: unexpected type, use Uint8Array
      
      at checkArrayTypes (node_modules/factom/node_modules/tweetnacl/nacl-fast.js:2151:13)
      at Function.Object.<anonymous>.nacl.sign.keyPair.fromSeed (node_modules/factom/node_modules/tweetnacl/nacl-fast.js:2313:3)
      at TransactionBuilder.input (node_modules/factom/src/transaction.js:209:38)
      at buildTransactionWithFees (node_modules/factom/src/send.js:73:10)
      at Object.createEntryCreditPurchaseTransaction (node_modules/factom/src/send.js:68:12)
          at <anonymous>
```

This is only happening when running this as a test - it cannot be replicated, otherwise.

## Reproducing

[here's the related **branch**](https://github.com/eolszewski/eventstore-eth/tree/enhancements/factom) of the repo I'm working with.

### Setup

You will need to create a `.env` file with the following defined (these are all community-known test values):
```
FACTOM_PK=FA2jK2HcLnRdS94dEcU27rF3meoJfpUcZPSinpb7AwQvPRY6RL1Q
FACTOM_SK=Fs3E9gV6DXsYzf7Fqx1fVBQPQXV695eP3k5XbmHEZVRLkMdD9qCK
EC_PK=EC2Hx7nxJMDQMPtXkrQuhdnFyUZvPrkSSLaNefXdMPiLjCQeshu7
EC_SK=Es2riHLhuNAvY5CrzrqPa9moZiHgnG32DpAXT2mspyD6K5jt8UaX
```

### Running Services
```
npm i
docker-compose up -d
```

### Running with node
```
node factom.js
```

### Running with react-scripts
```
npm test src/decentralized-storage/factom/
```

You will notice the error on the second run in `node_modules/factom/src/transaction.js:209`, but when you look into the types of the variables in question, they are the same between runs!

Help greatly appreciated.

**Comment by dchest** [comment]
As mentioned [here](https://github.com/PaulBernier/factomjs/issues/6#issuecomment-420158360), this looks like the testing framework has its own `Buffer` implementation that is not based on Uint8Array. All functions in TweetNaCl-js expect arguments to be `Uint8Arrays` and it checks for it here: https://github.com/dchest/tweetnacl-js/blob/master/nacl-fast.js#L2150

**Comment by eolszewski** [comment]
Whoops, opened this in the wrong place 😅.

Migrating...
