### ISSUE TITLE
use of Poly1305 with AEAD support (RFC 7539)

### ISSUE THREAD

**Issue by pohutukawa** [dchest/tweetnacl-js#149]
To use ChaCha20/Poly1305 with JOSE (JavaScript Object Signing and Encryption) as defined in RFC 7539, AEAD support is required. This will allow for encryption with an additional protected payload covered by the Poly1305 tag.

Unfortunately the IETF AEAD spec (RFC 7539) requires a different nonce length than what NaCl commonly uses.

We want to develop an extension to a JOSE library (not decided which one, yet) to support JWE encryption with ChaCha20/Poly1305, JWE encryption using X25519 (with an ephemeral sender key pair and using ChaCha20/Poly1305) as well as JWS signing using Ed25519.

We've got that stuff already availble for Python (using PyNaCl wrapping `libsodium`), but our needs for JavaScript still require an additional implementation.

Is it (fairly easily) possible to support AEAD compliant access, even it it's to the lower library core code only? For reference, in PyNaCl `nacl.bindings.crypto_aead.crypto_aead_chacha20poly1305_ietf_encrypt(message, aad, nonce, key)` and `nacl.bindings.crypto_aead.crypto_aead_chacha20poly1305_ietf_decrypt(ciphertext + tag, aad, nonce, key)` are exposed from `libsodium`.

**Comment by pohutukawa** [comment]
Or is this something (one of your projects as well, @dchest) be a solution?
https://github.com/StableLib/stablelib/blob/master/packages/chacha20poly1305/chacha20poly1305.ts

The question would be: How stable is the currently not so stable implementation? How suitable/fast is it in comparison with TweetNaCl.js on the use of ChaCha20/Poly1305?

This is, BTW, for the purpose of an open source identity system. Though, a liberal licence is appreciated (which this has with the MIT licence), so that it can be used from within proprietary code as well.

**Comment by dchest** [comment]
Yeah, tweetnacl-js doesn't have ChaCha, as it's pure port of the original TweetNaCl. StableLib implementation is fine: I don't plan on changing anything major in it, it has tests, and works well, it just needs better documentation, so feel free to use it. Performance is on par with tweetnacl-js, or even faster.

**Comment by pohutukawa** [comment]
Sweet, thanks for that. We'll give StableLib a stab then.
