### ISSUE TITLE
PyNACL compatibility?

### ISSUE THREAD

**Issue by pplanel** [dchest/tweetnacl-js#150]
I'm trying to integrate this lib with PyNacl in the backend, but I'm not sure If their are compatible, the message comes \0\0\0\0\0\0\0 always:
https://gist.github.com/pplanel/ba5a4b6e1324092565f224d86140151c

**Comment by dchest** [comment]
Add ```console.log(Uint8Array.from(card_info));``` before calling `nacl.box` and you'll see the problem. You're not serializing card info properly into Uint8Array.

**Comment by pplanel** [comment]
You're right. I've updated the gist serializing the card info with JSON.stringify but no luck, I receive a value from the decrypt but it comes with a lot of null (\0000) and not decoded.
https://gist.github.com/pplanel/ba5a4b6e1324092565f224d86140151c

**Comment by dchest** [comment]
You can't convert string to Uint8Array with .from(). You can use
back.util.decodeUTF8

**Comment by pplanel** [comment]
Are you talking about the encrypt_card function?

**Comment by pplanel** [comment]
You can comment on the gist

**Comment by dchest** [comment]
Basically, what you want to do is to pass a Uint8Array with your data to the encryption function. You're currently passing wrong data. Before even checking if encryption works, make sure the message you're trying to encrypt is correct. What nacl.box needs is a Uint8Array with data. If your data is a string (from JSON.stringify), you need to convert it to Uint8Array. `Uint8Array.from()` doesn't do it: it expects an array or iterable as input, but you're passing a UTF-16 encoded string. Check out this example on how to

**Comment by dchest** [comment]
Basically,  

```js
let message = nacl.box(nacl.util.decodeUTF8(card_info), nonce, public_key, keys.secretKey)
```

**Comment by pplanel** [comment]
It works! Thanks!
