### ISSUE TITLE
A: is there a difference between Scalar aerosol and golang?  

### ISSUE THREAD

**Issue by BigEgret** [dchest/tweetnacl-js#152]
let key = Buffer.allocUnsafe(32)
 let iv = Buffer.allocUnsafe(32)
 for (let i=0;i<32;i++){
      key[i] = i+32;
      iv[i] = i+35;
  }
nacl.scalarMult(key , iv ) ;
Different from golang?

**Comment by dchest** [comment]
Sorry, I don't understand your question, and your example code doesn't make any sense. If you'd like to report a bug in TweetNaCl-js, please provide example code that fails, with excepted results that it doesn't produce. If you'd like to ask a question on how to use cryptography or this library, please use StackOverflow or similar places, as GitHub is our issue tracker, not a support forum.
