### ISSUE TITLE
Encrypt via public key and decrypt via private key

### ISSUE THREAD

**Issue by evgeny-s** [dchest/tweetnacl-js#153]
Hello, everybody.
Is it possible to perform public key encryption flow?
https://en.wikipedia.org/wiki/Public-key_cryptography

1. Alice generates a message.
2. Alice encrypts it with Bob's public key. 
3. Alice sends a message to Bob (via an insecure channel).
4. Bob gets the message.
5. Bob can decrypt this message **only** with his private key.

I can't find proper method inside this lib. Could you please tell me if some workaround exists?
Thank you in advance.

**Comment by dchest** [comment]
Hello! This question is too broad for this issue tracker, please ask on StackOverflow.

**Comment by KrishnaPG** [comment]
Did you find answer for this? Looking for same information. It should be part of documentation on how to use the API. What is the series of API calls to make such that we can achieve the flow mentioned

**Comment by evgeny-s** [comment]
This can be done with `box` method:
https://github.com/dchest/tweetnacl-js#naclboxmessage-nonce-theirpublickey-mysecretkey

But you need to have the key pair for the side who encrypt the message. This is `mySecretKey` parameter.

**Comment by KrishnaPG** [comment]
Than you @evgeny-s 

The `box` method does "two-side" encryption, so to speak (i.e. theirPublicKey + mySecretKey)

The requirement is: just encrypt with `theirPublicKey` (no need to prove who is the sender). 

Only the receiver need to be established, not the sender. How to achieve it with this library?

**Comment by dchest** [comment]
@KrishnaPG  generate a random key pair, use box with the generated private key and recipient's public key, then attach the generated public key along with the message. Recipient receives the public key and message, and uses them along with their private key to decrypt.

**Comment by KrishnaPG** [comment]
Thanks @dchest . Yes, throw away keys are possible, but I was trying to avoid it, as it will unnecessarily increase the size + CPU execution.

In the underlying code, may be in `nacl.js` or somewhere, is there is no method to specifically instruct the library to only encrypt with publicKey or secretKey? For example, the [node-rsa](https://www.npmjs.com/package/node-rsa) package has these methods, such as
`````
keyPair.encrypt(buffer, [encoding], [source_encoding]);
keyPair.encryptPrivate(buffer, [encoding], [source_encoding]); // use private key for encryption

keyPair.decrypt(buffer, [encoding]);
keyPair.decryptPublic(buffer, [encoding]); // use public key for decryption
`````
The ` box` method would, then, be just a wrapper that uses a combination of these. 

Tried to go through the code to see if I can figure it out, but unfortunately it is too cryptic for me to understand.

**Comment by dchest** [comment]
This is not a limitation of library: elliptic curve cryptography is different from RSA, it uses Diffie-Hellman-like construction to derive a shared key.

**Comment by dchest** [comment]
Yes.

**Comment by KrishnaPG** [comment]
For those who visit this page later, this anonymous sender functionality is achievable through sealed box functions, such as [crypto_box_seal](https://download.libsodium.org/doc/public-key_cryptography/sealed_boxes) available in libSodium. The advantage is:

1. Sender will not have access to the ephemeral private key that created the sealed box
2. It does not require passing the public key of the sender explicitly, as the ciphertext already includes this information. Hence public key is not visible to anyone else

TweetNacl should consider exposing similar API.

**Comment by dchest** [comment]
> RSA has limitation on the message length (hence, we use AES to encrypt the full message, and do RSA on the AES key).

No limitation (well, to be precise 2^72 bytes).

> Does the box method internally takes care of long messages automatically?

As you can see from the API, it allocates both input and output Uint8Arrays.

> For example, can we use the box function on, say, a large text file content?

Yes, if you have enough memory (I believe JS runtimes are limited to 1 GB Uint8Arrays). You may consider https://github.com/dchest/nacl-stream-js

> For those who visit this page later, this anonymous sender functionality is achievable through sealed box functions, such as crypto_box_seal available in libSodium. The advantage is:

It implements what I suggested (plus the calculation of nonce by hashing public keys).

> 1. Sender will not have access to the ephemeral private key that created the sealed box

The sender does have access (it encrypts the message with it), it's just not available via API before it gets "destroyed".

> 2. It does not require passing the public key of the sender explicitly, as the ciphertext already includes this information. Hence public key is not visible to anyone else

This is wrong: the public key is prepended to the ciphertext, thus everyone has access to it:

```
ephemeral_pk ‖ box(m, recipient_pk, ephemeral_sk, nonce=blake2b(ephemeral_pk ‖ recipient_pk))
```

Regarding implementing crypto_box_seal, I replied here: https://github.com/dchest/tweetnacl-js/issues/102
