### ISSUE TITLE
Getting the base x25519 point, by multiplying by scalar of 1

### ISSUE THREAD

**Issue by borisreitman** [dchest/tweetnacl-js#155]
I have created a 32-byte array and set the rightmost bit to the value 1.   Why is it when I plug into  "scalarMultiply.base()"  I get a point that is not 9 ? Isn't that the base point? 

```
function test_nacl(){
  var one_big = bigInt(1);
  var one = bigint_to_X25519_scalar( one_big );
  console.log("one: ", decimal_string(one));

  var p = nacl.scalarMult.base(one);
  console.log("p: ", decimal_string(p)); // should be 9 ? 
}
```

Full reproducible code attached.  Download nacl.js and BigInteger.js and place in the same folder this file. Also rename extension to .html.

[test_one.html.txt](https://github.com/dchest/tweetnacl-js/files/2770804/test_one.html.txt)

**Comment by dchest** [comment]
In X25519, some key bits are set as follows: https://github.com/dchest/tweetnacl-js/blob/master/nacl.js#L392-L393

If I comment out those lines, and just log Uint8Arrays without using your conversion utils (e.g. `var one = new Uint8Array(32); one[0] = 1;`), I get:

```
one:  Uint8Array(32) [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
p:  Uint8Array(32) [9, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
```
 So, 1) there's probably some issue with your conversion utilities, 2) X25519 private key is always divisible by 8. Per RFC 7748:

>   For X25519, in order to decode 32 random bytes as an integer scalar, set the three least significant bits of the first byte and the most significant bit of the last to zero, set the second most significant bit of the last byte to 1 and, finally, decode as little-endian.

**Comment by borisreitman** [comment]
That's what I was missing, the order is little-endian. I was using it as big-endian.  Thanks.
