### ISSUE TITLE
new user of TweetNaCl.js

### ISSUE THREAD

**Issue by mgfck3** [dchest/tweetnacl-js#158]
Could You please add to list the project Bozon.cc which uses Your great lib?
Thank You.
https://bozon.cc

**Comment by dchest** [comment]
Thanks for letting me know. In order to now grow README too much, I've created this wiki page so that everyone could add their own projects (I've added yours): https://github.com/dchest/tweetnacl-js/wiki/Who-uses-TweetNaCl.js I'll eventually link to this page from README.

**Comment by mgfck3** [comment]
Thank You, Dmitry.
