### ISSUE TITLE
Adding Context (up to 255 bytes) string

### ISSUE THREAD

**Issue by NN-Binary** [dchest/tweetnacl-js#167]
Hi,

I'm looking to do a context similar to what's available in many libs such as this one in Haskell, rust, java...:
http://hackage.haskell.org/package/cryptonite-0.25/src/cbits/decaf/include/decaf/ed448.h
https://docs.rs/crate/ed25519-dalek/1.0.0-pre.1/source/src/public.rs
 * @param [in] context A "context" for this signature of up to 255 bytes.

Can you provide a way to do that?

Thanks :)

**Comment by dchest** [comment]
Sorry, this would be an invasive change to crypto internals that is not within the original goal of TweetNaCl-js ("The primary goal of this project is to produce a translation of TweetNaCl to JavaScript which is as close as possible to the original C implementation, plus a thin layer of idiomatic high-level API on top of it.")
