### ISSUE TITLE
API support for AAD?

### ISSUE THREAD

**Issue by kdenhartog** [dchest/tweetnacl-js#169]
Is it possible to add an API that supports the use of authenticated additional data? We're looking to implement JWEs based on this library, but the use of the protected header is making it not possible. What would be the best approach to handle this?

**Comment by dchest** [comment]
Unfortunately, NaCl doesn't have a defined AEAD construction, only AE (XSalsa20Poly1305). You can try ChaCha20Poly1305 (e.g. [@stablelib/chacha20poly1305](https://github.com/StableLib/stablelib/blob/master/packages/chacha20poly1305/chacha20poly1305.ts)), but note that its nonce is short (12 bytes), so you may want XChaChaPoly https://download.libsodium.org/doc/secret-key_cryptography/aead/chacha20-poly1305 if using a random nonce.

Sometimes, for short headers people just include a copy of them in the encrypted data, and then compare it after decryption with the attached plain-text headers, but this is riskier and I don't think would work very well for JWE.
