### ISSUE TITLE
Why the use of Float64Array is ok?

### ISSUE THREAD

**Issue by valerini** [dchest/tweetnacl-js#181]
gf element is stored as Float64Array in tweetnacl-js, while it is stored as i64 in tweetnacl.c.

Is it a problem that Float64 CAN NOT hold precisely unsigned integers of length more than 53 bits? Is 53 bits enough to carry the arithmetic operations correctly?

**Comment by dchest** [comment]
Yes, it enough: it uses only up to 48 bits.
