### ISSUE TITLE
module in php

### ISSUE THREAD

**Issue by sherifomran** [dchest/tweetnacl-js#182]
is there any hope to have it as php module ?

i tried converting it using https://github.com/endel/js2php/ parser, but i don't know how to test it.
could you please help.

thank you

**Comment by dchest** [comment]
No. But PHP 7.2 comes with libsodium extension, e.g. https://www.php.net/manual/en/function.sodium-crypto-box-seal.php

**Comment by dchest** [comment]
There's also https://github.com/paragonie/sodium_compat if you don't have libsodium extension.
