### ISSUE TITLE
Is there API for Point addition?

### ISSUE THREAD

**Issue by SHiftLin** [dchest/tweetnacl-js#184]
Scalar multiplication is provided. From my understanding, for a Point P, and a integer c, it returns cP=P+P+....+P. But For Point P and Q, can I compute P+Q through tweetnacl?

**Comment by valerini** [comment]
Yeh, function add(p, q) gives point addition (see https://github.com/dchest/tweetnacl-js/blob/1b61c87b6df9859ac136c3c025cdb974220c333c/nacl.js#L638).
