### ISSUE TITLE
Export scalarMult

### ISSUE THREAD

**Issue by rg911** [dchest/tweetnacl-js#189]
Hi any reason  why the `scalarMult` method is not exported but only the crypto_scalarMult? Any chance to export the scalarMult: https://github.com/dchest/tweetnacl-js/blob/5bf1ff5fa15e89ae249401b0d5aa54c5c5955041/nacl.js#L680 ?

**Comment by dchest** [comment]
https://github.com/dchest/tweetnacl-js#scalar-multiplication

**Comment by dchest** [comment]
Oh, you mean for the Edwards curve? It's indeed not exported, that's how it is in TweetNaCl. I don't recommend using internals at all, since they are not suitable for the general use.
