### ISSUE TITLE
"Math keeps changing" concerns

### ISSUE THREAD

**Issue by taoeffect** [dchest/tweetnacl-js#190]
According to [this article](https://macwright.org/2020/02/14/math-keeps-changing.html), different versions of Node can produce different numerical results for calculations like `Math.pow(1/3, 3)`.

How does this affect the encryption of JS crypto as a whole, and does this affect tweetnacl-js specifically? Is secure JS with "future-proof" crypto simply impossible? Or am I misunderstanding?

Any insights/help with understanding this greatly appreciated!

**Comment by dchest** [comment]
Not an issue for TweetNaCl.js, since we deal with integers (in Salsa/Poly bit operations are on 32-bit numbers, in Curve/Ed 25519 they can be larger, we use `Math.floor` after division in some places).

**Comment by dchest** [comment]
As for JS crypto as a whole, I doubt there are any implementations that use fractional numbers. I'm aware of Poly1305 implementation that used doubles (I ported it to Go once), but those probably can't be implemented in JS.

**Comment by taoeffect** [comment]
OK thanks so much @dchest for taking the time to explain that! That's somewhat reassuring. I hope you're right that this doesn't impact JS crypto. Feel free to close this issue or leave it open. Either way it may be helpful info for others.
