### ISSUE TITLE
No PRNG

### ISSUE THREAD

**Issue by JeffWScott** [dchest/tweetnacl-js#191]
Getting the below error thrown in Node.js after bundling.
```
Error: no PRNG
    at randombytes (e:\Lamden\lamden-js\dist\bundle.js:10456:68)
    at crypto_sign_keypair (e:\Lamden\lamden-js\dist\bundle.js:12363:33)
    at Function.nacl.sign.keyPair (e:\Lamden\lamden-js\dist\bundle.js:12744:3)
    at generate_keys (e:\Lamden\lamden-js\dist\bundle.js:12874:28)
```

This is what I'm calling:

```
kp = nacl.sign.keyPair();
```

**Comment by dchest** [comment]
Here's the code: https://github.com/dchest/tweetnacl-js/blob/master/nacl.js#L1150-L1176

What are you bundling it with, and for what system? If you're bundling it for the web browser and running in Node, it doesn't have browser's `crypto.getRandomValues` and probably doesn't have `require`.

**Comment by JeffWScott** [comment]
@dchest Yeah it's for the broswer...  I'm bundling with rollup and adding the Node builtins plugin, which includes the node crypto module.

**Comment by dchest** [comment]
So, it seems like rollup doesn't support dynamic `require` for commonjs modules (there's a plugin for that I think?). Also, TweetNaCl.js doesn't need Node's crypto module shim for running in browser (unless you do something with it, of course).

Anyway, a bundle for the browser is a bundle for the browser, not Node :-)

**Comment by JeffWScott** [comment]
I think it was because I was using import instead of requre...  it all might actually be working now.

Thanks for the assistance :)
