### ISSUE TITLE
deno support [suggestion]

### ISSUE THREAD

**Issue by jamilservicos** [dchest/tweetnacl-js#195]
I recommend creating a repository compatible with deno:
https://deno.land/

**Comment by dchest** [comment]
I don’t think pure JS crypto library is of any good for Dino, just like for Node (TweetNacl.js supports Node, of course, but mostly for ease of testing). Instead, I’d recommend bindings for native libraries.

**Comment by jamilservicos** [comment]
I believe that to have better compatibility it is best to use both ends (backend and frontend).
the module's own structure is made for nodejs.
just create a separate repository with structure for deno, to be compatible with backend deno.
but it’s just a suggestion.

**Comment by dchest** [comment]
JavaScript crypto should only be used in contexts where it’s impossible to use native - mostly, web browsers (for cases where WebCrypto API is not suitable). There are no compatibility issues between eg libsodium or TweetNaCl.c and TweetNaCl.js.

If you want to use a single code base in projects, I’d recommend using a shim that would call either TweetNaCl.js or bindings to native crypto library (eg libsodium) depending on runtime.
