### ISSUE TITLE
Compatability with NaCl?

### ISSUE THREAD

**Issue by Niklas81** [dchest/tweetnacl-js#203]
Not a bug, just a question, as I haven't been able to find this elsewhere:

If I use Tweetnacl.js to encrypt a string/json-object, will I then be able to decrypt it in Go using x/crypto/nacl?

Meaning this:
https://pkg.go.dev/golang.org/x/crypto/nacl/

In other words, is this implementation compatible with pure NaCl? Does version of both products matter?

**Comment by dchest** [comment]
It is compatible.

**Comment by Niklas81** [comment]
Awesome, thanks!
