### ISSUE TITLE
Use box.keyPair for XEdDSA / VXEdDSA signatures?

### ISSUE THREAD

**Issue by zbo14** [dchest/tweetnacl-js#206]
I'm guessing this functionality is outside the scope of the package. Still wondering how one would go about doing this (mb requires other packages)?

**Comment by dchest** [comment]
Is XEdDSA the original signing scheme from Signal/Axolotl protocol? If so, here's a modified version that implements it: https://github.com/wavesplatform/curve25519-js

**Comment by dchest** [comment]
Alternatively, if you don't need the actual XEdDSA, but just want a single key pair for DH and signing, you can use signing key pair and convert it to box (DH) key pair using this package: https://github.com/dchest/ed2curve-js

**Comment by zbo14** [comment]
@dchest Awesome thank you!
