### ISSUE TITLE
Please also export "pack" function in nacl.lowlevel

### ISSUE THREAD

**Issue by tetratorus** [dchest/tweetnacl-js#214]
in some instances, we may want to import 32 byte partial private keys 

this requires using a custom modified version of crypto_sign_keypair, which uses the pack function, and the pack function isn't exported. reimplementing using nacl.lowlevel primitives is troublesome.

would be great if every function was exported in nacl.lowlevel IMHO, since the purpose of lowlevel is to expose the internal methods so that implementers can reuse them for custom requirements

**Comment by dchest** [comment]
Will `nacl.sign.keyPair.fromSeed` work for your purpose?

**Comment by CMEONE** [comment]
@tetratorus @dchest I believe #218 resolves this issue, please take a look.
