### ISSUE TITLE
Improve Readability of Code Snippets in README

### ISSUE THREAD

**Issue by mostafa-kheibary** [dchest/tweetnacl-js#265]
I was reading the readme and the code snippets in the README are hard to distinguish from the rest of the text, making it difficult to read and understand the examples provided.

I'd like to contribute by improving the formatting of the code snippets. This could include:

- Using Markdown code blocks for better syntax highlighting.
- Adding appropriate spacing around the code snippets.

**Comment by dchest** [comment]
Thanks, but there aren't really a lot of code snippets in the README and they look fine without multiple colors.

**Comment by mostafa-kheibary** [comment]
Ok, thank you for the response
