### ISSUE TITLE
Base64 encoding doesn't work in Safari's web workers

### ISSUE THREAD

**Issue by dchest** [dchest/tweetnacl-js#44]
Reported here:

https://github.com/kaepora/miniLock/issues/53

It turns out in Safari `atob` and `btoa` are not available in web workers:

https://bugs.webkit.org/show_bug.cgi?id=55663

Not sure if we should re-implement base64 ourselves or just wait for Safari to fix it (probably the latter). Until then, it's good to have this issue opened so that people know about this and use something else for base64 encoding if they use web workers in Safari.

**Comment by anri-asaturov** [comment]
http://code.google.com/p/gflot/source/browse/trunk/flot/base64.js?r=153 can solve this

**Comment by mdp** [comment]
This also happens React Native for iOS since it's using a webkit engine that doesn't support `atob` and doesn't have `Buffer`

**Comment by dchest** [comment]
@mdp thanks for letting me know!

I think I'll deprecate *utils* package sometime in the future. As explained in docs:

> Encoding/decoding functions are provided for convenience. They are correct, however their performance and wide compatibility with uncommon runtimes is not something that is considered important compared to the simplicity and size of implementation. You can use third-party libraries if you need to.

**Comment by alax** [comment]
@mdp React Native doesn't use Webkit, it just uses JavaScriptCore, which is a wrapper around Webkit's Javascript engine. That also means that you won't have secure random number generator, so unless you've implemented one yourself, TweetNacl won't even work under React Native.

**Comment by mdp** [comment]
@dchest Yeah that's fair, I just wanted to add to this thread in case anyone else runs across it.

@alax Thanks, this is really good to know. I was only using it for decryption, but it's something I'll definitely keep in mind.

**Comment by alax** [comment]
@mdp Ahh, gotcha. Yeah, you are right, decryption would be 100% fine.

**Comment by dchest** [comment]
@alax @mdp yep, only key generation needs random numbers: secretbox, cryptobox, signing all work fine without PRNG if you already have keys.

**Comment by dchest** [comment]
For everyone's information, this was recently fixed in WebKit https://bugs.webkit.org/show_bug.cgi?id=158576
