### ISSUE TITLE
Allow use of nodejs Buffer objects instead of Uint8Array where applicable

### ISSUE THREAD

**Issue by RainaBatwing** [dchest/tweetnacl-js#59]
Uint8Array is a great choice for browser-based apps like miniLock. In nodejs apps, the standard is to use node's Buffer system, which is used by many other npm libraries and in all IO including networks and local filesystem operations. While it is easy to convert types with `new Uint8Array(buffer)` and `new Buffer(uint8array)` these are both unsatisfying because both conversions create copies of data - not references. Copying can be slow for larger pieces of data, but maybe more importantly it means secrets like secretKeys and nonces end up being duplicated whenever a conversion is needed, leaving them floating around for garbage collection unless lots of care (and extra code) is written to zero those resources out. This provides a dangerous incentive for people to write less secure code. Even people with good intentions would have a difficult time keeping track of it all.

Skimming the tweetnacl-js source it seems like Buffer and Uint8Array both provide equivalent functionality for crypto uses. One difference is that node Buffers are not preinitialized with zeros. Buffers contain garbage data from system memory similar to a malloc. This provides a performance boost but might make detecting bugs more difficult when cryptographically random input is expected and sort-of random garbage data is erroneously received.

I'd like tweetnacl-js to offer a way to switch it from Uint8Array to Buffer objects, and I'd prefer it default to Buffer when it's available. Both Uint8Array and Buffer provide [] byte accessors and a 'length' property. I think that's all tweetnacl-js needs?

At a minimum, it would be helpful if functions like nacl.box() would accept Buffer objects as inputs. Converting the output would still be annoying, but not nearly as annoying as having to convert all the inputs and manage their safe erasure.

**Comment by RainaBatwing** [comment]
Any thoughts on implementing this? It's something I could do if you think it's a good idea. It would personally improve a lot of code clarity and help speed up my own uses of tweetnacl-js. I think it maybe less work for me to implement this in tweetnacl-js than continue working around this feature not existing.

I'm feeling fond of the buffer testing idea in my last comment.

**Comment by dchest** [comment]
@RainaBatwing yes, please go ahead.

**Comment by RainaBatwing** [comment]
Making some progress on this issue at https://github.com/RainaBatwing/tweetnacl-js/tree/nacl.setReturnType

I'd like some feedback on these subarray changes which affect low level functions: https://github.com/RainaBatwing/tweetnacl-js/commit/82f8bb4ea5cf099fa83cf5c6504c6e54ef3187b8#diff-ede9f1016292e622d247dc33617dd1cbL1371

Node's Buffer object doesn't implement a subarray function, but it's slice() is equivalent to Uint8Array's subarray()

**Comment by dchest** [comment]
I think it's better to focus on leave two kinds: `Uint8Array` and `Buffer`. Since we already distinguish between Node and browser environments for random number generation, maybe let's just make it `nacl.setUseBuffer(true)` to use Buffer for everything, and require `Buffer` in `checkArrayTypes` in this case?

**Comment by RainaBatwing** [comment]
I'm struggling to see why locking the project to only using constructors assigned to window.Buffer or global.Buffer would be helpful? Is the purpose to reduce the lines of code to keep under 100 tweets?

**Comment by dchest** [comment]
It's mostly to avoid the excess flexibility. I don't think there are any other objects which are useful here apart from `Uint8Array` of `Buffer`, and if something comes up later, we can always reconsider this decision, but if we add such flexibility to add any other API compatible object, we'll always have to consider that some user passed some object we didn't think of. (Also, it avoids having to allocate an object during the type check).

**Comment by RainaBatwing** [comment]
`nacl.setUseNodeBuffer(true)` isn't really less flexible, it's just more inconvenient and brittle. We can't use the Object.prototype.toString.call trick to identify a node-like Buffer. A user or XSS attacker can run `global.Buffer = MyCustomType` or `window.Buffer = MyCustomType` before calling a nacl high level function and we wouldn't be able to tell the difference.

I've implemented a strict interface with type checking which verifies objects users are attempting to use are compatible with the library, regardless of their name. Rather than supporting a single class of objects, we shift to supporting a single interface of objects. I mean Interface in the Java sense.

In `nacl-fast.js` my `checkArrayTypes` implementation only instantiates a copy the first time, then caches a successful result. That caching was omitted in `nacl.js` preferring compactness and simplicity over speed. I could add the caching logic to `nacl.js` if speed or memory use is a concern.

**Comment by RainaBatwing** [comment]
Here's another way to make tweetnacl-js accept Buffers

```javascript
var prev = Object.prototype.toString;
Object.prototype.toString = function() { return Buffer.isBuffer(this) ? '[object Uint8Array]' : prev.call(this) };
Buffer.prototype.subarray = Buffer.prototype.slice;
```

Making tweetnacl-js return buffers is even easier!

```
> global.Uint8Array = function(a) { return new Buffer(a) }
[Function]
> new Uint8Array('abc')
<Buffer 61 62 63>
```

**Comment by dchest** [comment]
I'm not concerned about how it behaves in XSS, I'm just concerned that it's too flexible, and we'll have to support some weird use cases in the future. But your analogy with interfaces I think convinced me :-) I'll check your nacl-fast version, maybe it's worth doing the same in normal nacl. Could you, perhaps, do a pull request with your branch, even if unfinished, so that we can discuss changes there and maybe review them line-by-line. Thanks!

**Comment by RainaBatwing** [comment]
Okay

**Comment by dchest** [comment]
io.js implements `Buffer` via `Uint8Array`, and accepts `ArrayBuffer` in constructor (https://github.com/nodejs/io.js/pull/2002/commits). Can we just leave TweetNaCl-js with `Uint8Array`s everywhere — it's so simple to have one data type for byte arrays?

**Comment by Downchuck** [comment]
@dchest I agree that sticking to Uint8Array is the simplest thing to do. For those that are looking to squeeze more performance, it may just make sense for them to use libsodium and such.

**Comment by dchest** [comment]
Node.js 4.x now has Buffers backed by Uint8Arrays.
