### ISSUE TITLE
tweetnacl-js incompatible with tweetnacl & nacl

### ISSUE THREAD

**Issue by leonpegg** [dchest/tweetnacl-js#64]
box and secretbox are incompatible with the core nacl and tweetnacl releases as it does not  zero padded the boxes although I don't quite understand why the core releases to this and prefect your implementation it make the library unusable as it is not interoperable with the core libraries

**Comment by dchest** [comment]
Not true, they are compatible and interoperable. Zero padding is a C implementation quirk to allow you to provide preallocated space to functions, so that they don't call `malloc`. How do you them in C to make boxes incompatible? FIY, original C++ API also doesn't use zero padding.

**Comment by leonpegg** [comment]
Thanks for the clarification so if i drop the zeros from the output tweetnacl.js will be able to decrypt and when i pass into my C app i need to zero pad?

**Comment by dchest** [comment]
Yes. In fact, the high-level API, which is documented, is a wrapper around a low-level API, which uses similar API to original (because TweetNaCl-js is a direct port of the original tweetnacl): https://github.com/dchest/tweetnacl-js/blob/master/nacl.js#L992

**Comment by leonpegg** [comment]
Thanks was able to modify the C source and make it work :D

**Comment by dchest** [comment]
@leonpegg great :+1:
