### ISSUE TITLE
synchronous key derivation function?

### ISSUE THREAD

**Issue by fruiz500** [dchest/tweetnacl-js#68]
I'd like to be able to use tweetnacl-js starting with user-supplied passwords, which then are inflated to 256 bits by some sort of KDF. The one I like the most is scrypt, and the best implementation I've been able to find is yours, but it is asynchronous and I need it to be synchronous (even at the expense of waiting) because there is a lot of code that follows the KDF.

Sometimes the KDF needs to be called several times before the algorithm is done, which makes asynchronous a nightmare. Is there a synchronous KDF like scrypt that you can recommend?

**Comment by dchest** [comment]
@fruiz500 If you don't mind editing [scrypt-async-js](https://github.com/dchest/scrypt-async-js), you can easily turn it into a synchronous function by removing two lines from [`interruptedFor` function](https://github.com/dchest/scrypt-async-js/blob/master/scrypt-async.js#L417-L428):

```diff
   function interruptedFor(start, end, step, fn, donefn) {
     (function performStep() {
-      setTimeout(function() {
         fn(start, start + step < end ? start + step : end);
         start += step;
         if (start < end)
           performStep();
         else
           donefn();
-        }, 0);
     })();
   }
```

You can then do this:

```javascript
var result;
scrypt(passwordArray, saltArray, logN, r, 32, step, function(x) { result = x; }, "base64");
// result now contains base64-encoded password hash
```

Alternatively, use some other scrypt implementation, such as [tonyg/js-scrypt](https://github.com/tonyg/js-scrypt).

**Comment by fruiz500** [comment]
Thanks! That worked.

I'm switching to your version of scrypt for the next version of my PassLok app. I've run some tests, and your program is roughly twice as fast at the one by joe-invincible (also on Github), which I was using until now.

Good job!
