### ISSUE TITLE
shorter/longer nonce

### ISSUE THREAD

**Issue by fruiz500** [dchest/tweetnacl-js#69]
I see that a 24-byte length is hardcoded for the nonce value. But looking through the original NaCl paper, it appears that it doesn't need to be this way. I have an application where it would be advantageous to use a shorter nonce because of space limitations, and the 24 bytes eat too much of it.

Is there a way to specify a nonce length different from 24 bytes?

**Comment by dchest** [comment]
Sure, just set unused bytes to zero.
