### ISSUE TITLE
TypeError: unexpected type [object String], use Uint8Array

### ISSUE THREAD

**Issue by atuljain** [dchest/tweetnacl-js#71]
I am working first time in security using nodejs library's and i am using example code and getting this error

/sysusers/tradeboox/node_modules/ed2curve/node_modules/tweetnacl/nacl.js:941
       throw new TypeError('unexpected type ' + t + ', use Uint8Array');
             ^
TypeError: unexpected type [object String], use Uint8Array
    at checkArrayTypes (/sysusers/tradeboox/node_modules/ed2curve/node_modules/tweetnacl/nacl.js:941:14)
    at Function.nacl.sign.open (/sysusers/tradeboox/node_modules/ed2curve/node_modules/tweetnacl/nacl.js:1090:3)
    at Object.<anonymous> (/sysusers/tradeboox/E1.js:23:30)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3

My code is 

// Generate new sign key pair. 
var nacl = require("/sysusers/tradeboox/node_modules/ed2curve/node_modules/tweetnacl/nacl.js");
var myKeyPair = nacl.sign.keyPair();
 
// Share public key with a peer.
console.log(myKeyPair.publicKey);
 
// Receive peer's public key. 
var theirPublicKey = myKeyPair.publicKey ;
// ... receive 
 
// Sign a message. 
var message = nacl.util.decodeUTF8('Hello!');
var signedMessage = nacl.sign(message, myKeyPair.secretKey);
 
// Send message to peer. They can now verify it using 
// the previously shared public key (myKeyPair.publicKey). 
// ... 
 
// Receive a signed message from peer and verify it using their public key. 
var theirSignedMessage = 'Hello Worlds Atul Jain';
// ... receive 
var theirMessage = nacl.sign.open(theirSignedMessage, theirPublicKey);
if (theirMessage) {
  // ... we got the message ... 
}
 
// Encrypt a message to their public key. 
// But first, we need to convert our secret key and their public key 
// from Ed25519 into the format accepted by Curve25519. 
// 
// Note that peers are not involved in this conversion -- all they need 
// to know is the signing public key that we already shared with them. 
 
var theirDHPublicKey = ed2curve.convertPublicKey(theirPublicKey);
var myDHSecretKey = ed2curve.convertSecretKey(myKeyPair.secretKey);
 
var anotherMessage = nacl.util.decodeUTF8('Keep silence');
var encryptedMessage = nacl.box(anotherMessage, theirDHPublicKey, myDHSecretKey);
 
// When we receive encrypted messages from peers, 
// we need to use converted keys to open them. 
 
var theirEncryptedMessage = '';
// ... receive 
var decryptedMessage = nacl.box.open(theirEncryptedMessage, theirDHPublicKey, myDHSecretKey);

**Comment by atuljain** [comment]
is there any good tutorial available for better practise

**Comment by dchest** [comment]
> var theirSignedMessage = 'Hello Worlds Atul Jain';

You didn't decode from string to bytes, should be

```javascript
var theirSignedMessage = nacl.util.decodeUTF8('Hello Worlds Atul Jain');
```

I'm not aware of any tutorials.

**Comment by sapanjeetkaur** [comment]
Hello , i am also trying same code with changes but still getting same error on another line 

// Generate new sign key pair.
var ed2curve = require("ed2curve")
var nacl = require("tweetnacl/nacl.js");
var myKeyPair = nacl.sign.keyPair();
// Share public key with a peer.
console.log(myKeyPair.publicKey); // Receive peer's public key.
var theirPublicKey = myKeyPair.publicKey ; // ... receive
// Sign a message.
var message = nacl.util.decodeUTF8('Hello!');
var signedMessage = nacl.sign(message, myKeyPair.secretKey);
// Send message to peer. They can now verify it using
// the previously shared public key (myKeyPair.publicKey).
// Receive a signed message from peer and verify it using their public key.
var theirSignedMessage = nacl.util.decodeUTF8('Hello, How are you World!!!!!!!!!');// ... receive
var theirMessage = nacl.sign.open(theirSignedMessage, theirPublicKey);
if (theirMessage) {
}
console.log(theirMessage)
// Encrypt a message to their public key.
// But first, we need to convert our secret key and their public key
// from Ed25519 into the format accepted by Curve25519.
// Note that peers are not involved in this conversion -- all they need
// to know is the signing public key that we already shared with them.
var theirDHPublicKey = ed2curve.convertPublicKey(theirPublicKey);
var myDHSecretKey = ed2curve.convertSecretKey(myKeyPair.secretKey);
//console.log(theirDHPublicKey)
//console.log(myDHSecretKey)
var anotherMessage = nacl.util.decodeUTF8('Keep silence');
var encryptedMessage = nacl.sign.open(anotherMessage, theirDHPublicKey);
// When we receive encrypted messages from peers,
// we need to use converted keys to open them.

var theirEncryptedMessage = nacl.util.decodeUTF8('Encryptd Message'); // ... receive
var decryptedMessage = nacl.sign.open(theirEncryptedMessage, myDHSecretKey);

Getting same error but on another line 

throw new TypeError('unexpected type ' + t + ', use Uint8Array');
             ^
TypeError: unexpected type [object Function], use Uint8Array
    at checkArrayTypes (/home/admin/node_modules/tweetnacl/nacl.js:941:14)
    at Object.nacl.secretbox (/home/admin/node_modules/tweetnacl/nacl.js:990:3)
    at Object.nacl.box (/home/admin/node_modules/tweetnacl/nacl.js:1036:15)
    at Object.<anonymous> (/home/admin/Desktop/A/EE.js:31:29)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)

**Comment by dchest** [comment]
@sapanjeetkaur are you sure you posted the corresponding code for the error? There's no `nacl.box` call anywhere. What's on line 31 in EE.js?

**Comment by sapanjeetkaur** [comment]
sorry, i posted wrong code , 

this is my updated code

// Generate new sign key pair.
var ed2curve = require("ed2curve")
var nacl = require("tweetnacl/nacl.js");
var myKeyPair = nacl.sign.keyPair();
// Share public key with a peer.
console.log(myKeyPair.publicKey); // Receive peer's public key.
var theirPublicKey = myKeyPair.publicKey ; // ... receive
// Sign a message.
var message = nacl.util.decodeUTF8('Hello!');
var signedMessage = nacl.sign(message, myKeyPair.secretKey);
// Send message to peer. They can now verify it using
// the previously shared public key (myKeyPair.publicKey).
// Receive a signed message from peer and verify it using their public key.
var theirSignedMessage = nacl.util.decodeUTF8('Hello Worlds Atul Jain');// ... receive
var theirMessage = nacl.sign.open(theirSignedMessage, theirPublicKey);
if (theirMessage) {
}
console.log(theirMessage)
// Encrypt a message to their public key.
// But first, we need to convert our secret key and their public key
// from Ed25519 into the format accepted by Curve25519.
// Note that peers are not involved in this conversion -- all they need
// to know is the signing public key that we already shared with them.
var theirDHPublicKey = ed2curve.convertPublicKey(theirPublicKey);
var myDHSecretKey = ed2curve.convertSecretKey(myKeyPair.secretKey);
//console.log(theirDHPublicKey)
//console.log(myDHSecretKey)
var anotherMessage = nacl.util.decodeUTF8('Keep silence');
var encryptedMessage = nacl.box(anotherMessage, theirDHPublicKey);
// When we receive encrypted messages from peers,
// we need to use converted keys to open them.

var theirEncryptedMessage = nacl.util.decodeUTF8('Encryptd Message'); // ... receive
var decryptedMessage = nacl.box.open(theirEncryptedMessage, myDHSecretKey);

**Comment by dchest** [comment]
`nacl.box` and `nacl.box.open` requires 4 arguments: please see https://github.com/dchest/tweetnacl-js#naclboxmessage-nonce-theirpublickey-mysecretkey

You can check [this example page](https://dchest.github.io/tweetnacl-js/#/box) and the corresponding code in `gh-pages` branch https://github.com/dchest/tweetnacl-js/blob/gh-pages/app.js#L278.

**Comment by sapanjeetkaur** [comment]
HI , 
when i passed 4 arguments on both method than it raised me another erro r

Error: bad secret key size

**Comment by dchest** [comment]
It tells you that the secret key size is wrong, so you're passing something different there.

Perhaps, a better place to ask such questions would be http://stackoverflow.com/, as there are not enough visitors in this issue tracker.
