### ISSUE TITLE
TweetNaCl used in PassLok 2.2

### ISSUE THREAD

**Issue by fruiz500** [dchest/tweetnacl-js#74]
I though you'd like to know that I'm using your impressive library in the new version of PassLok, which can be found here:
https://github.com/fruiz500/passlok
I'm also using scrypt-async (with the trick you suggested to make it synchronous), and ed2curve.
I'm listing you everywhere that credit is given, but please let me know if this is unsatisfactory.
Great job!

**Comment by dchest** [comment]
Thank you for letting me know! BTW, no credit is necessary at all ;-)
