### ISSUE TITLE
Forward secrecy / Axolotl

### ISSUE THREAD

**Issue by alax** [dchest/tweetnacl-js#82]
Hey guys, I've written a barebones javascript implementation of Axolotl that uses TweetNacl heavily internally. I'm just posting it here because it seems like there might be a lot of overlap between people using TweetNacl and people interested in forward secrecy / axolotl ratcheting.

https://github.com/alax/forward-secrecy

Thanks! :smile:

**Comment by dchest** [comment]
Awesome, thanks! I've added it to the [new section in README](https://github.com/dchest/tweetnacl-js#third-party-libraries-based-on-tweetnacljs).
