### ISSUE TITLE
Question regarding license

### ISSUE THREAD

**Issue by mijikim** [dchest/tweetnacl-js#85]
Hello,

The CCO-1.0 license in tweetnacl-js makes it difficult to use the module and all of its dependents in an enterprise context.  Would it be possible for the license to change to a license approved by Open Source Initiative (ie. MIT, Apache, BSD...)?

Thank you,
Mi Ji

**Comment by dchest** [comment]
CC0 is not a license, it's a public domain dedication (with the workaround kinda-license, in case there's no public domain in your jurisdiction).

Regardless of [OSI bullshit about public domain](http://opensource.org/faq#public-domain), the authors of this software tell you to do anything you want with this software. If your enterprise can't do anything it wants with this software, I'm sorry.

**Comment by dchest** [comment]
FYI, if the phrase "CC0" scares enterprise people, and "Public domain" not, I can change it back to say the latter (I changed it due to #81 request).

**Comment by dchest** [comment]
To add: the original NaCl/TweetNaCl, which TweetNaCl.js is the port of, is in public domain.

**Comment by mijikim** [comment]
@dchest If you can change it back to "public domain", that would be appreciated. The legal team is requesting this and unfortunately I don't have a personal input into their decisions. Thank you again!

**Comment by dchest** [comment]
Done, thanks for your feedback.

**Comment by jsmartfo** [comment]
Is there anything stopping this being MIT license? the public domain license does cause certain enterprise issues. 

Here is the problem that arises, mods like fsevents use this code, seeing as its a dependency now of fsevents it also stops that being used and so on up the chain. 

Anything you can do to help here would be great.

**Comment by dchest** [comment]
Yes. The original C code is public domain and I'd like to keep the spirit of it by releasing my port to the public domain. If you're worried about public domain, you won't be able to use this library even if I released it under any other license, as it's a derivative work from TweetNaCl, which is in public domain.

**Comment by jsmartfo** [comment]
Okay I see.... bummer. Thanks for quick response.
