### ISSUE TITLE
Update license

### ISSUE THREAD

**Issue by tracker1** [dchest/tweetnacl-js#93]
Would it be possible to update/adjust the license to CC0 or WTFPL, and include a LICENSE.txt .. we're having trouble getting this module (dependency for phantomjs) approved via our legal team...

Please!?!  TIA...

**Comment by dchest** [comment]
Sorry, no: https://github.com/dchest/tweetnacl-js/issues/85#issuecomment-180475852

>  If you're worried about public domain, you won't be able to use this library even if I released it under MIT or any other license, as it's a derivative work from TweetNaCl, which is in public domain.

**Comment by tracker1** [comment]
I'm not worried about it...  honestly, I hate that legal compliance is an entirely removed department, we aren't even redistributing this, it's used for development.  what a pain in the neck.

**Comment by dchest** [comment]
Yes, I understand (read it as "if your legal department is concerted ..."). Sorry about this :(

**Comment by dchest** [comment]
Perhaps you can try to convince them by sending this (from original TweetNaCl author): https://cr.yp.to/publicdomain.html

**Comment by dchest** [comment]
Interesting how your legal department is okay with CC0, but this guy's not: https://github.com/dchest/tweetnacl-js/issues/85
