### ISSUE TITLE
Include a license in LICENSE.md

### ISSUE THREAD

**Issue by CharlieHess** [dchest/tweetnacl-js#98]
Placing the license in `COPYING.txt` forces some tools to add manual overrides:
```
Packages detected with unsafe licenses:
{"name":"tweetnacl@0.14.3","repository":"git+https://github.com/dchest/tweetnacl-js","license":"SEE LICENSE IN COPYING.txt","source":"package.json"}
```
It would be better, and more standard, to have the Public Domain text listed in `LICENSE.md`. GitHub will even do it for you now.

**Comment by dchest** [comment]
I suggest you to file an issue with such tool. Public domain is not a license. See #96.

**Comment by 45678** [comment]
i get frusterated with `npm` insisting that a package should have a license, and i agree with the sentiment @dchest expressed in the previous message.

for what it is worth, i’ve found the [Unlicense](https://unlicense.org/) to be a helpful in situations like these. You can specify it in a package.json file with: `"license": "Unlicense"` to get `npm` to shut the fuck up. And it provides a gentle introduction to the concepts of Public Domain and Copyright for people who might be confused.

**Comment by dchest** [comment]
@45678 thanks for suggestion, but I'd like to keep it as it is for the reasons explained in earlier issues. NPM should not complain as they specifically mention the wording I use "SEE LICENSE IN COPYING.txt": 

> Sorry, license should be a valid SPDX license expression without "LicenseRef", "UNLICENSED", or "SEE LICENSE IN <filename>".

This issue is about some tool, which doesn't recognize this wording.

**Comment by dchest** [comment]
@CharlieHess I think the issue of this tool is not that it can't read files other than LICENSE.md, that it won't be useful anyway. TweetNaCl-js is in public domain, so we have some custom text in COPYING.txt (which people asked for) saying you can do anything you like.

@45678 on the second thought, Unlicense wording is similar to what we have now, so I may change it. Thanks!
